name: footmoney
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  gap: ^3.0.1
  sizer: ^2.0.15
  intl: ^0.19.0
  intl_phone_number_input:
    git:
      url: https://github.com/Shahidbangash/intl_phone_number_input.git
      ref: develop
  modal_bottom_sheet: ^3.0.0
  shared_preferences: ^2.3.2
  pie_chart: ^5.4.0
  easy_date_timeline: ^1.1.3
  http: ^1.2.2
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/gifs/
    - assets/images/
    - assets/images/login.png
    - assets/images/forgot2.png
    - assets/images/register2.png
    - assets/images/ligue.png
    - assets/images/africa.png
    - assets/images/olympique.png
    - assets/images/joueur.png
    - assets/images/wave.jpeg
    - assets/images/moov.png
    - assets/images/orange.png
    - assets/images/mtn.png
    - assets/images/maillotone.png